version: "3.3"
services:

  backoffice_frontend:
    restart: always
    build: ..//backoffice-front/ 
    container_name: backoffice-front-container
    stdin_open: true 
    tty: true        
    ports:
      - 3003:3000
    depends_on:
      - users_dev_db
    expose:
      - 3000
    volumes:
      - ..//backoffice-front:/webgui
    environment:
      - REACT_APP_BACKEND_DIRECTION=http://localhost:3001
      - PORT=3000
    networks:
      - my_network

  api_gateway:
    restart: always
    build: ..//api_gateway/ 
    container_name: api-gateway-container
    stdin_open: true 
    tty: true
    entrypoint: ../start-reload.sh        
    ports:
      - 3005:3000
    expose:
      - 3000
    volumes:
      - ..//api_gateway:/app
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      - USERS_BASE_URL=http://users-ms-container:3000
    networks:
      - my_network

  backoffice_api_gateway:
    restart: always
    build: ..//backoffice_api_gateway/ 
    container_name: backoffice-api-gateway-container
    stdin_open: true 
    tty: true
    entrypoint: ../start-reload.sh        
    ports:
      - 3006:3000
    expose:
      - 3000
    volumes:
      - ..//backoffice_api_gateway:/app
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      # - BACKOFFICE_BASE_URL=http://users-ms-container:3007
    networks:
      - my_network

  users_backend:
    restart: always
    build: ..//users/ 
    container_name: users-ms-container
    stdin_open: true 
    tty: true
    entrypoint: ../start-reload.sh # Para que se haga el live reload        
    ports:
      - 3001:3000
    expose:
      - 3000
    volumes:
      - ..//users:/app
    links:
      - users_dev_db
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:grupo1@users-ms-dev-db-container:5432/postgres
      - POSTGRES_PASSWORD=grupo1
      - LOG_LEVEL=debug
    depends_on:
      - users_dev_db
    networks:
      - my_network

  users_dev_db:
    image: postgres
    container_name: users-ms-dev-db-container
    environment:
      - POSTGRES_PASSWORD=grupo1
    expose:
      - 5432
    ports:
      - 6543:5432
    networks:
      - my_network

  trips_backend:
    restart: always
    build: ..//trips/ 
    container_name: trips-backend-container
    stdin_open: true 
    tty: true
    entrypoint: ../start-reload.sh # Para que se haga el live reload        
    ports:
      - 3002:3000
    expose:
      - 3000
    volumes:
      - ..//trips:/app
    links:
      - trips_dev_db
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:grupo1@trips-ms-dev-db-container:5432/postgres
      - POSTGRES_PASSWORD=grupo1
      - LOG_LEVEL=debug
    depends_on:
      - trips_dev_db
    networks:
      - my_network

  trips_dev_db:
    image: postgres
    container_name: trips-ms-dev-db-container
    environment:
      - POSTGRES_PASSWORD=grupo1
    expose:
      - 5432
    ports:
      - 6544:5432
    networks:
      - my_network

  backoffice_backend:
    restart: always
    build: ..//backoffice/ 
    container_name: backoffice-backend-container
    stdin_open: true 
    tty: true
    entrypoint: ../start-reload.sh # Para que se haga el live reload        
    ports:
      - 3007:3000
    expose:
      - 3000
    volumes:
      - ..//backoffice:/app
    links:
      - backoffice_dev_db
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:grupo1@backoffice-ms-dev-db-container:5432/postgres
      - POSTGRES_PASSWORD=grupo1
      - LOG_LEVEL=debug
    depends_on:
      - backoffice_dev_db
    networks:
      - my_network

  backoffice_dev_db:
    image: postgres
    container_name: backoffice-ms-dev-db-container
    environment:
      - POSTGRES_PASSWORD=grupo1
    expose:
      - 5432
    ports:
      - 6545:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge