version: "3.3"
services:

  dev_db:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=grupo1
    expose:
      - 5432
    ports:
      - 6543:5432
    networks:
      - my_network

  users_backend:
    restart: always
    build: ./users/ 
    container_name: users-backend-container
    stdin_open: true 
    tty: true        
    ports:
      - 3001:3000
    expose:
      - 3000
    volumes:
      - ..//users:/app
    links:
      - dev_db
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:grupo1@postgres-container:5432/postgres
      - POSTGRES_PASSWORD=grupo1
      - LOG_LEVEL=debug
      - GUNICORN_CMD_ARGS="--reload"
    depends_on:
      - dev_db
    networks:
      - my_network

  backoffice_frontend:
    restart: always
    build: ./backoffice-front/ 
    container_name: backoffice-frontend-container
    stdin_open: true 
    tty: true        
    ports:
      - 3003:3000
    depends_on:
      - dev_db
      # - users_backend
    expose:
      - 3000
    volumes:
      - ..//backoffice-front:/webgui
    environment:
      - REACT_APP_BACKEND_DIRECTION=http://localhost:3001
      - PORT=3000
    networks:
      - my_network

  api_gateway:
    restart: always
    build: ./api_gateway/ 
    container_name: api-gateway-container
    stdin_open: true 
    tty: true        
    ports:
      - 3005:3000
    expose:
      - 3000
    volumes:
      - ..//api_gateway:/app
    environment:
      - PORT=3000
      - LOG_LEVEL=debug
      - USERS_BASE_URL=http://users-backend-container:3000
      - GUNICORN_CMD_ARGS="--reload"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge